#!/bin/sh
#
# ipcam        Starts mjpg-stream to serve the camera stream.
#

umask 077

start() {
	modprobe bcm2835-v4l2
	printf "Starting camera server: "
	mjpg_streamer -b -i "input_raspicam.so -x 1280 -y 720 -fps 15" -o "output_http.so -w /usr/share/mjpg-streamer/www"
	echo "OK"
}
stop() {
	printf "Stopping camera server: "
	killall raspistill
	killall mjpg_streamer
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

